name: hello-world
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  my-job:
    runs-on: ubuntu-latest
    #runs-on: ["${{github.run_id}}", self-hosted, "${{needs.set-outputs.outputs.instancetype}}"]
    steps:
      - name: sayhi
        run: echo "Hello World!"
      - name: print
        run: echo ${{ github.job }}
      - name: sleep
        run: sleep 6
